#!/usr/bin/env python3
"""Generate the built-in 50x26 LVGL I1 Fighter frames from extracted Kyo BMPs."""

from __future__ import annotations

import argparse
import struct
from pathlib import Path

WIDTH = 50
HEIGHT = 26
BAYER = ((0, 2), (3, 1))
INK = (0, 1, 3, 4)
GROUPS = {"idle": 4, "kick_l": 3, "roll_f": 5, "oni_yaki_l": 7}


def read_bmp(path: Path) -> tuple[int, int, list[list[int]]]:
    data = path.read_bytes()
    if data[:2] != b"BM":
        raise ValueError(f"not a BMP: {path}")
    offset = struct.unpack_from("<I", data, 10)[0]
    width, height = struct.unpack_from("<ii", data, 18)
    stride = (width + 3) & ~3
    rows = []
    for y in range(height):
        start = offset + (height - 1 - y) * stride
        rows.append(list(data[start : start + width]))
    return width, height, rows


def render(path: Path) -> bytes:
    source_width, source_height, source = read_bmp(path)
    scale = min(WIDTH / source_width, HEIGHT / source_height)
    width = max(1, round(source_width * scale))
    height = max(1, round(source_height * scale))
    left = (WIDTH - width) // 2
    top = HEIGHT - height
    canvas = [[0] * WIDTH for _ in range(HEIGHT)]
    for y in range(height):
        sy = min(source_height - 1, int(y / scale))
        for x in range(width):
            sx = min(source_width - 1, int(x / scale))
            level = INK[source[sy][sx]]
            canvas[top + y][left + x] = int(BAYER[(top + y) & 1][(left + x) & 1] < level)
    # Palette index 0 is transparent. Index 1 is black and can be recolored
    # white by the widget when a fullscreen battle action is active.
    packed = bytearray((0, 0, 0, 0, 0, 0, 0, 0xFF))
    for row in canvas:
        for start in range(0, WIDTH, 8):
            value = 0
            for bit, pixel in enumerate(row[start : start + 8]):
                value |= pixel << (7 - bit)
            packed.append(value)
    return bytes(packed)


def array(name: str, data: bytes) -> str:
    lines = []
    for start in range(0, len(data), 12):
        lines.append("    " + ", ".join(f"0x{v:02x}" for v in data[start : start + 12]) + ",")
    return f"""static const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST uint8_t {name}_map[] = {{
{chr(10).join(lines)}
}};

const lv_image_dsc_t {name} = {{
    .header.cf = LV_COLOR_FORMAT_I1,
    .header.w = {WIDTH},
    .header.h = {HEIGHT},
    .data_size = {len(data)},
    .data = {name}_map,
}};
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--bitmaps", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    blocks = ["/* Generated by scripts/generate_fighter_images.py. */", "#include <lvgl.h>"]
    for group, count in GROUPS.items():
        for index in range(count):
            name = f"fighter_{group}_{index}"
            blocks.append(array(name, render(args.bitmaps / group / f"{index:03d}.bmp")))
    args.output.write_text("\n\n".join(blocks) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
